### PR TITLE
Add missing service discovery in nginx config

### PR DESCRIPTION
**Pull request by waja**
See https://docs.nextcloud.com/server/15/admin_manual/issues/general_troubleshooting.html#service-discovery
Rules as suggest in https://docs.nextcloud.com/server/15/admin_manual/installation/nginx.html

The last rule is needed by the (new) [Social App](https://apps.nextcloud.com/apps/social), see: webfinger_social

### CODE REVIEW

**Comment by lachmanfrantisek** [comment]
I have one wish related to this.

Is it possible to enhance the nginx config for the [cms_pico](https://github.com/nextcloud/cms_pico) as well?

Their docs for the Apache config can be seen [here](https://github.com/nextcloud/cms_pico/wiki/Admin-Settings#apache-configuration).

---

I've been playing with that a bit, but not make it work.

Thanks!

**Comment by hoellen** [comment]
@waja thanks for the PR!

@lachmanfrantisek you can try the following configuration for nginx: 
```
location /sites/ {
        rewrite /sites/(.*) /apps/cms_pico/pico/$1 break;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_pass unix:/php/run/php-fpm.sock;
    }
```
I don't know, if I want to include nginx configurations for every single app. Maybe it fits better in your reverse proxy configuration? 
If you want to discuss this further, please open a new issue.

**Comment by waja** [comment]
> I don't know, if I want to include nginx configurations for every single app. Maybe it fits better in your reverse proxy configuration?

I even was thinking about this and I discovered that https://github.com/containous/traefik seems to only support one redirect rule (okay, with regular expressions). So I thought it would be good to have those (official) apps supported in the image itself.
Anyway, I think the cms_pico app is a way less common to implement those rewrites in the app container itself.

Just my 2 cents.

**Comment by hoellen** [comment]
Yes, I've got the same opinion on that. I merged this PR, because its in the official Nextcloud documentation. Every other rewrite should be done in the reverse proxy.

**Comment by lachmanfrantisek** [comment]
@waja @hoellen Thanks for the info and config example. It would be nice to have it in this image but I understand that you cannot support all apps.

**Comment by lachmanfrantisek** [comment]
@waja Does the error in Social app disappeared after this addition?

I've finally updated the nextcloud to 15 and installed the Social app, but the warning is still there.

Both original and redirected url returns `missing resource`, so the problem is probably somewhere else.

My instance is in the root of the domain and I am using **jwilder/nginx-proxy** image for forwarding if it is important.

Is it OK or I can have some problems with this setup?

Thank you!

**Pull request merged**
