### PR TITLE
Update Nextcloud to 22.2.0, 21.0.5 and 20.0.13

### PR DESCRIPTION
**Pull request by waja**

### CODE REVIEW

**Comment by hoellen** [comment]
Thanks

**Comment by ziirish** [comment]
Hello,

There seem to be a problem with the `hoellen/nextcloud:22` image that was build a couple hours ago.
When starting it up we can see the message `OC\HintException: [0]: Downgrading is not supported and is likely to cause unpredictable issues (from 22.1.1.2 to 22.0.0.11) ()`

The `version.php` file is showing this:

```
/nextcloud # cat version.php
<?php
$OC_Version = array(22,0,0,11);
$OC_VersionString = '22.0.0';
$OC_Edition = '';
$OC_Channel = 'stable';
$OC_VersionCanBeUpgradedFrom = array (
  'nextcloud' =>
  array (
    '21.0' => true,
    '22.0' => true,
  ),
  'owncloud' =>
  array (
    '10.5' => true,
  ),
);
$OC_Build = '2021-07-05T20:58:46+00:00 c67e1420c8f741bfa43db08fcc295ec3b156fff8';
$vendor = 'nextcloud';
```

**Comment by waja** [comment]
I can not reproduce this issue. I updated a couple of instances successfully (and no one failed).

**Comment by ziirish** [comment]
hm, yes, nevermind... I downloaded the `hoellen/nextcloud:22.0` image instead of the `22.2`...

**Pull request merged**
