### PR TITLE
Adding enviroment variable SESSION_GC_MAXLIFETIME

### PR DESCRIPTION
**Pull request by waja**
When setting 'autologout' => true, this will happen after
session_lifetime.
The maximum possible time is limited by the session.gc_maxlifetime, so
it makes sense to be able to adjust this value.
(see
https://github.com/nextcloud/server/pull/26007/commits/296332efa38d25e18ffe066843d707bbc835068c)

### CODE REVIEW

**Comment by waja** [comment]
Is there anything that should be changed to get this merged?

**Comment by hoellen** [comment]
Why should this be configurable as Docker environment variable? 
You can easily set this PHP config by mounting a file as volume to the path `/php/conf.d/session.ini` with the following content:
```
session.gc_maxlifetime=1440
``` 
I don't necessarily want to increase the number of configuration settings.

**Comment by waja** [comment]
> Why should this be configurable as Docker environment variable?

For the same reason this is be done with the other environment variables adjusting the PHP behavior. For convenient.

**Comment by hoellen** [comment]
I'm going to get rid of the other environment variables, too.

**Comment by waja** [comment]
> I'm going to get rid of the other environment variables, too.

hehe ... okay, go for it! :)

**Pull request closed without merging**
