### PR TITLE
Update nextcloud to 22.1.1

### PR DESCRIPTION
**Pull request by eloo**

### CODE REVIEW

**Comment by hoellen** [comment]
Thanks!

**Comment by ziirish** [comment]
Hello,

First of all, Thank you for your work on these docker images!
I'm not sure this is the best place to report you that, maybe I can fill an issue instead if you prefer but it looks like your docker images are not built on a regular basis anymore as you can see [here](https://hub.docker.com/r/hoellen/nextcloud/tags?page=1&ordering=last_updated). Maybe the problem is related to [this](https://www.docker.com/blog/changes-to-docker-hub-autobuilds/) blog post?

**Comment by hoellen** [comment]
Yes you're right. Docker closed unfortunately their autobuild feature. 
My plan is to use Github Actions for building the images and also adopting the new changes from the original author Wonderfall. But so far I haven't had time for it (and it will stay that way for the time being).

Nevertheless, I will update the images manually today. Thanks for reminding me.

**Comment by waja** [comment]
@hoellen do you accept PRs on this?

**Comment by hoellen** [comment]
I would be very happy to receive a PR for this.

**Comment by waja** [comment]
Hmm ... I totally forgot that you have multiple docker images in one repository with multiple tags. You can have a look into https://github.com/waja/docker-nginx/blob/development/.github/workflows/release.yml for an example to build one image for multiple archtitectures. I think you need to combine this with a [build matrix](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows) (and somehow handle that only images are build when the relevant `Dockerfile` is changed).

**Pull request merged**
